### ISSUE TITLE
Second time running in Replit is showing errors

### ISSUE THREAD

**Issue by SatyamSSJ10** [bhigginsuk/discord-rss-fetcher#28]
/RSS$ npm start

> discord-rss-feed@4.1.3 start /home/runner/RSS
> node ./dist/index.js --name rss-fetcher

/home/runner/RSS/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/RSS/node_modules/discord.js/src/client/BaseClient.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-rss-feed@4.1.3 start: `node ./dist/index.js --name rss-fetcher`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-rss-feed@4.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-25T12_38_14_311Z-debug.log
~/RSS$

**Comment by brhigginsuk** [comment]
Perhaps Replit is using an older version of JavaScript? The nullish coalescing operator (??) was only introduced in ECMAScript 2020, so older versions wouldn't support it.

Either way, the logs show the issue is with code from discord.js, which is the Discord library I used, and not something I created.
